### ISSUE TITLE
关于char_language_model.py中的xw_plus_b.

### ISSUE THREAD

**Issue by bringtree** [soloice/tf-tutorial#1]
大佬你好。 你的代码很赞! 
首先有2个观点，应该都没错吧。
x*w
![image](https://user-images.githubusercontent.com/20106478/43639468-e631f8ec-974e-11e8-9bbe-164c24e6b90e.png)
w*x
`基变化 .原本x 中放的是 A空间的基向量的各个权重。 然后W是用B空间基向量表示A空间的基向量。 经过乘 完后得到的结果就是x在 B空间的向量的各个权重。这个说法对吗
`

然后我的问题是？
然后在char_language_model.py中的xw_plus_b这里是x*w，怎么解释比较这一步计算比较合理？
x*w 训练的时候 一直是在训练w 左边把在输入的x投影到指定的长度？
w*x 训练的时候 是在训练 x怎么转化到一个合适的空间 后面在去接个分类器分类？
感觉怪怪的。然后 我在另外一个项目中试了w*x 结果并不work,(重新看了下线代发现 这样这样空间的维度并没有发生提升，都是分布在这个空间的某个平面上而已，难怪不work)
改 x*w 才work。这是为什么？

**Comment by soloice** [comment]
1、你想多了。xW 就是把 W'x' 转置了一下。x 代表一个样本（但是是行向量，数学公式里多用列向量表示，即 x'），然后 W'x' 就是用 W' 对 x' 进行线性变换，最后结果再转置一下就是 xW。

2、xw_plus_b 就是数学公式 Wx + b 的 batch 形式。
在数学公式 Wx+b 里，x 和 b 都是列向量；如果把很多 x 组合在一起，变成矩阵 X（每列代表一个样本），然后计算 WX，再给结果的每一列加上列向量 b，就可以一次算一个 batch。
但是问题在于，TF 查询 embedding 是查出来的结果是行向量，给一个矩阵加  bias 的时候是给矩阵的每一行（而非列）都加上这个 bias，所以把数学公式 WX + b 转置一下，变成了 xw_plus_b（其中的参数 X 每行代表一个样本）。

xw 就是“在训练 x怎么转化到一个合适的空间 后面在去接个分类器分类”。

**Comment by soloice** [comment]
你看看这个：[MNIST-TF](https://www.tensorflow.org/versions/r1.0/get_started/mnist/beginners)

里面有一段 "This is flipped from when we multiplied them in our equation"，应该说得比较清楚了。
